package career.assistant.application.service;
import career.assistant.application.entity.*;import career.assistant.application.repository.ApplicationRepository;import career.assistant.jobscore.repository.JobScoreRepository;import career.assistant.security.AuthenticatedOwner;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import java.util.*;
@Service public class AutoApplyWorkerService {
 private final ApplicationRepository apps;private final JobScoreRepository scores;private final AutoApplyExecutionService execution;private final AutoApplyEligibilityService eligibility;private final boolean enabled,dry,scheduler;
 public AutoApplyWorkerService(ApplicationRepository a,JobScoreRepository s,AutoApplyExecutionService e,AutoApplyEligibilityService x,@Value("${career.application.auto-apply-enabled:false}")boolean en,@Value("${career.application.dry-run:true}")boolean dr,@Value("${career.application.scheduler-enabled:false}")boolean sc,@Value("${career.application.minimum-score:75}")java.math.BigDecimal m){apps=a;scores=s;execution=e;eligibility=x;enabled=en;dry=dr;scheduler=sc;}
 public WorkerResult run(boolean confirmation){if(!enabled)return result(WorkerOutcome.DISABLED,null,"Auto-apply is disabled");if(dry)return result(WorkerOutcome.DRY_RUN_PROTECTED,null,"Dry-run protection is enabled");String owner;try{owner=AuthenticatedOwner.required();}catch(SecurityException e){owner=null;}return process(owner,confirmation,false);}
 public WorkerResult runForOwner(String owner,boolean confirmation){if(!enabled)return result(WorkerOutcome.DISABLED,null,"Auto-apply is disabled");if(dry)return result(WorkerOutcome.DRY_RUN_PROTECTED,null,"Dry-run protection is enabled");if(owner==null||owner.isBlank())return result(WorkerOutcome.REVIEW_REQUIRED,null,"Authenticated owner is required");return process(owner,confirmation,false);}
 public WorkerResult runScheduled(){if(!schedulerAllowed())return result(WorkerOutcome.DISABLED,null,"Scheduler is disabled");return process(null,true,true);}
 private WorkerResult process(String owner,boolean confirmation,boolean scheduled){if(!confirmation)return result(WorkerOutcome.REVIEW_REQUIRED,null,"Explicit confirmation is required");List<Application> source=scheduled?apps.findByStatusAndOwnerSubjectIsNotNull(ApplicationStatus.READY_TO_APPLY):(owner==null?apps.findByStatus(ApplicationStatus.READY_TO_APPLY):apps.findByStatusAndOwnerSubject(ApplicationStatus.READY_TO_APPLY,owner));List<Application> candidates=source.stream().filter(a->a.getOwnerSubject()!=null&&(scheduled||owner==null||owner.equals(a.getOwnerSubject()))).filter(a->eligibility.evaluate(a,a.getOwnerSubject()).eligible()).sorted(Comparator.comparing((Application a)->scores.findByJobAndOwnerSubject(a.getJob(),a.getOwnerSubject()).map(s->s.getScore()).orElse(java.math.BigDecimal.ZERO),Comparator.reverseOrder()).thenComparing(a->Optional.ofNullable(a.getReviewedAt()).orElse(a.getCreatedAt()),Comparator.nullsLast(Comparator.naturalOrder())).thenComparing(Application::getId,Comparator.nullsLast(Comparator.naturalOrder()))).toList();if(candidates.isEmpty())return result(WorkerOutcome.NO_ELIGIBLE_APPLICATION,null,"No eligible READY_TO_APPLY application");Application candidate=candidates.getFirst();var r=execution.executeForOwner(candidate.getId(),true,candidate.getOwnerSubject());if(r.state()==null)return result(WorkerOutcome.REVIEW_REQUIRED,r.applicationId(),r.blocker());if(r.state()==career.assistant.application.audit.SubmissionAttemptState.UNCERTAIN)return result(WorkerOutcome.UNCERTAIN,r.applicationId(),r.blocker());if(r.state()==career.assistant.application.audit.SubmissionAttemptState.REVIEW_REQUIRED)return result(WorkerOutcome.REVIEW_REQUIRED,r.applicationId(),r.blocker());return result(WorkerOutcome.PROCESSED,r.applicationId(),r.blocker());}
 public boolean schedulerAllowed(){return scheduler&&enabled&&!dry;}private WorkerResult result(WorkerOutcome o,UUID id,String reason){return new WorkerResult(o,id,reason);}public enum WorkerOutcome{DISABLED,DRY_RUN_PROTECTED,NO_ELIGIBLE_APPLICATION,DAILY_LIMIT_REACHED,PROCESSED,REVIEW_REQUIRED,UNCERTAIN}public record WorkerResult(WorkerOutcome outcome,UUID applicationId,String safeReason){}
}
