package career.assistant.application.service;
import career.assistant.application.ats.PublicAtsAdapters;
import career.assistant.application.audit.*;
import career.assistant.application.entity.*;
import career.assistant.application.repository.ApplicationRepository;
import career.assistant.document.repository.*;
import career.assistant.jobscore.repository.JobScoreRepository;
import career.assistant.settings.SettingsRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.math.BigDecimal;
import java.util.*;
@Service public class AutoApplyEligibilityService {
 private final JobScoreRepository scores;private final SubmissionAttemptRepository attempts;private final SubmissionAttemptService attemptService;private final ResumeVersionRepository resumes;private final CoverLetterRepository letters;private final SettingsRepository profiles;private final BigDecimal minimum;private final int dailyLimit;
 public AutoApplyEligibilityService(ApplicationRepository apps,JobScoreRepository scores,SubmissionAttemptRepository attempts,SubmissionAttemptService attemptService,ResumeVersionRepository resumes,CoverLetterRepository letters,SettingsRepository profiles,@Value("${career.application.minimum-score:75}")BigDecimal minimum,@Value("${career.application.max-real-submissions-daily:1}")int dailyLimit){this.scores=scores;this.attempts=attempts;this.attemptService=attemptService;this.resumes=resumes;this.letters=letters;this.profiles=profiles;this.minimum=minimum;this.dailyLimit=dailyLimit;}
 public Eligibility evaluate(Application a,String owner){List<String>b=new ArrayList<>();if(a==null)return new Eligibility(false,List.of("NOT_FOUND"));if(a.getOwnerSubject()==null)return new Eligibility(false,List.of("LEGACY_RECORD_REQUIRES_RECREATION"));if(owner==null||!owner.equals(a.getOwnerSubject()))b.add("NOT_FOUND");if(a.getStatus()!=ApplicationStatus.READY_TO_APPLY)b.add("NOT_READY");var score=scores.findByJobAndOwnerSubject(a.getJob(),a.getOwnerSubject()).orElse(null);if(score==null||!a.getOwnerSubject().equals(score.getOwnerSubject()))b.add("SCORE_OWNERSHIP_MISMATCH");else if(score.getScore()==null||score.getScore().compareTo(minimum)<0)b.add("SCORE_BELOW_THRESHOLD");String location=(String.valueOf(a.getJob().getLocation())+" "+String.valueOf(a.getJob().getCountry())).toLowerCase(Locale.ROOT);if(!(location.contains("uae")||location.contains("dubai")||location.contains("abu dhabi")||location.contains("sharjah")))b.add("NON_UAE");if(PublicAtsAdapters.parseAshbyUrl(a.getJob().getJobUrl()).isEmpty())b.add("UNSUPPORTED_ATS");if(profiles.findByOwnerSubject(a.getOwnerSubject()).filter(this::complete).isEmpty())b.add("PROFILE_INCOMPLETE");if(a.getResumeVersionId()==null||resumes.findByIdAndOwnerSubject(a.getResumeVersionId(),a.getOwnerSubject()).filter(r->r.isCustomized()&&r.getStoragePath()!=null&&!r.getStoragePath().isBlank()).isEmpty())b.add("RESUME_INVALID");if(a.getCoverLetterId()==null||letters.findByIdAndOwnerSubject(a.getCoverLetterId(),a.getOwnerSubject()).filter(l->l.getStoragePath()!=null&&!l.getStoragePath().isBlank()).isEmpty())b.add("COVER_LETTER_INVALID");if(!attemptService.dailyLimitAvailable(a.getOwnerSubject(),dailyLimit))b.add("DAILY_LIMIT");if(attempts.existsByApplicationIdAndStateIn(a.getId(),List.of(SubmissionAttemptState.IN_PROGRESS,SubmissionAttemptState.CONFIRMED,SubmissionAttemptState.UNCERTAIN)))b.add("BLOCKING_ATTEMPT");return new Eligibility(b.isEmpty(),List.copyOf(b));}
 private boolean complete(career.assistant.settings.entity.UserSettings p){return ok(p.getLegalName())&&ok(p.getApplicationEmail())&&ok(p.getApplicationPhone())&&ok(p.getCurrentLocation())&&ok(p.getRelocation())&&ok(p.getVisaAnswer())&&ok(p.getSponsorshipAnswer())&&p.getNoticePeriodDays()!=null&&ok(p.getLinkedinUrl())&&ok(p.getConsentAnswers());}private boolean ok(String v){return v!=null&&!v.isBlank();}
 public record Eligibility(boolean eligible,List<String> blockerCodes){}
}
