"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useAuth} from "./auth-provider";
type Status="PENDING_REVIEW"|"READY_TO_APPLY"|"AUTO_APPLIED"|"MANUALLY_APPLIED"|"FAILED"|"REJECTED";
type Application={id:string;jobId:string;job:string;company:string;sourceUrl:string;score:number;confidence:string;matchedSkills:string[];missingSkills:string[];status:Status;resumeVersionId:string|null;coverLetterId:string|null;adapter:string|null;confirmationId:string|null;confirmationUrl:string|null;reason:string|null;appliedAt:string|null;createdAt:string};
type Letter={id:string;jobId:string;title:string;content:string;fileName:string;summary:string;createdAt:string};
const errorText=async(r:Response)=>{const b=await r.json().catch(()=>null) as {message?:string}|null;return b?.message||`Request failed (${r.status})`;};
const wanted:Partial<Record<string,Status[]>>={"Pending Review":["PENDING_REVIEW"],"Ready to Apply":["READY_TO_APPLY"],"Auto Applied":["AUTO_APPLIED"],"Failed Applications":["FAILED"],"Successfully Applied":["AUTO_APPLIED","MANUALLY_APPLIED"]};
export default function ApplicationWorkflow({apiBase,view}:{apiBase:string;view:string}){const {apiFetch,downloadFile}=useAuth();const [apps,setApps]=useState<Application[]>([]);const [letters,setLetters]=useState<Letter[]>([]);const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const load=useCallback(async()=>{try{const [a,l]=await Promise.all([apiFetch(`${apiBase}/applications`,{cache:"no-store"}),apiFetch(`${apiBase}/cover-letters`,{cache:"no-store"})]);if(!a.ok)throw new Error(await errorText(a));setApps(await a.json() as Application[]);if(l.ok)setLetters(await l.json() as Letter[]);}catch(e){setNotice(e instanceof Error?e.message:"Workflow could not be loaded");}},[apiBase,apiFetch]);useEffect(()=>{let ignore=false;Promise.all([apiFetch(`${apiBase}/applications`,{cache:"no-store"}),apiFetch(`${apiBase}/cover-letters`,{cache:"no-store"})]).then(async([a,l])=>{if(!a.ok)throw new Error(await errorText(a));const nextApps=await a.json() as Application[];const nextLetters=l.ok?await l.json() as Letter[]:[];if(!ignore){setApps(nextApps);setLetters(nextLetters);}}).catch(e=>{if(!ignore)setNotice(e instanceof Error?e.message:"Workflow could not be loaded");});return()=>{ignore=true;};},[apiBase,apiFetch]);
 const shown=useMemo(()=>wanted[view]?apps.filter(a=>wanted[view]!.includes(a.status)):apps,[apps,view]);
 const review=async(a:Application,approve:boolean)=>{setBusy(a.id);setNotice(null);try{const r=await apiFetch(`${apiBase}/applications/${a.id}/review`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({approve,reason:approve?"Manually approved after document review":"Rejected after manual review"})});if(!r.ok)throw new Error(await errorText(r));await load();}catch(e){setNotice(e instanceof Error?e.message:"Review failed");}finally{setBusy(null);}};
 const run=async(a:Application)=>{setBusy(a.id);setNotice(null);try{const r=await apiFetch(`${apiBase}/applications/${a.id}/run`,{method:"POST"});if(!r.ok)throw new Error(await errorText(r));const result=await r.json() as Application;setNotice(result.reason||"Dry run completed without submission.");await load();}catch(e){setNotice(e instanceof Error?e.message:"Dry run failed");}finally{setBusy(null);}};
 if(view==="Cover Letters")return <section className="panel"><div className="panelHead"><div><h2>Cover letters</h2><p>UAE-focused documents generated only from verified facts and matched skills.</p></div></div>{letters.length===0?<div className="state">No cover letters generated yet.</div>:<div className="resumeList">{letters.map(l=><article key={l.id}><div className="fileIcon">DOCX</div><div className="resumeMeta"><h3>{l.title}</h3><p>{l.summary}</p><p>{l.content}</p></div><div className="resumeActions"><button onClick={()=>void downloadFile(`${apiBase}/cover-letters/${l.id}/download?inline=true`,{inline:true})}>Preview</button><button onClick={()=>void downloadFile(`${apiBase}/cover-letters/${l.id}/download`,{filename:l.fileName})}>Download</button></div></article>)}</div>}</section>;
 return <section className="panel"><div className="panelHead"><div><h2>{view}</h2><p>Application packages remain private; all submission actions are dry-run protected by default.</p></div><button className="ghost" onClick={()=>void load()}>Refresh</button></div>{notice&&<div className="notice">{notice}</div>}{shown.length===0?<div className="state">No applications in this stage.</div>:<div className="resumeList">{shown.map(a=><article key={a.id}><div className="fileIcon">{Math.round(a.score)}%</div><div className="resumeMeta"><div><h3>{a.job} · {a.company}</h3><span className={`badge ${a.status.toLowerCase()}`}>{a.status.replaceAll("_"," ")}</span></div><p>Confidence: {a.confidence}{a.adapter?` · ${a.adapter}`:""}</p><div className="chips good">{a.matchedSkills.map(s=><span key={s}>✓ {s}</span>)}</div><div className="chips">{a.missingSkills.map(s=><span key={s}>{s}</span>)}</div>{a.reason&&<p>{a.reason}</p>}{a.confirmationId&&<p>Confirmation: {a.confirmationId}</p>}</div><div className="resumeActions">{a.resumeVersionId&&<><button onClick={()=>void downloadFile(`${apiBase}/resumes/${a.resumeVersionId}/download?inline=true`,{inline:true})}>Resume preview</button><button onClick={()=>void downloadFile(`${apiBase}/resumes/${a.resumeVersionId}/download`,{filename:"resume"})}>Resume download</button></>}{a.coverLetterId&&<><button onClick={()=>void downloadFile(`${apiBase}/cover-letters/${a.coverLetterId}/download?inline=true`,{inline:true})}>Letter preview</button><button onClick={()=>void downloadFile(`${apiBase}/cover-letters/${a.coverLetterId}/download`,{filename:"cover-letter"})}>Letter download</button></>}<a href={a.sourceUrl} target="_blank" rel="noreferrer">Source ↗</a>{a.status==="PENDING_REVIEW"&&<><button className="primary" disabled={busy===a.id} onClick={()=>void review(a,true)}>Approve</button><button className="danger" disabled={busy===a.id} onClick={()=>void review(a,false)}>Reject</button></>}{a.status==="READY_TO_APPLY"&&<button className="primary" disabled={busy===a.id} onClick={()=>void run(a)}>Run dry-run adapter</button>}</div></article>)}</div>}</section>}
