"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useAuth} from "./auth-provider";
import {workflowStatuses, type WorkflowStatus as Status} from "./lib/workflow-view";
type Application={id:string;jobId:string;job:string;company:string;sourceUrl:string;score:number;confidence:string;matchedSkills:string[];missingSkills:string[];locationFit:number|null;experienceFit:number|null;scoreExplanation:string|null;requiredFields:string[];missingRequiredAnswers:string[];status:Status;resumeVersionId:string|null;coverLetterId:string|null;adapter:string|null;confirmationId:string|null;confirmationUrl:string|null;reason:string|null;appliedAt:string|null;createdAt:string};
type Letter={id:string;jobId:string;title:string;content:string;fileName:string;summary:string;createdAt:string};
const errorText=async(r:Response)=>{const b=await r.json().catch(()=>null) as {message?:string}|null;return b?.message||`Request failed (${r.status})`;};
export default function ApplicationWorkflow({apiBase,view}:{apiBase:string;view:string}){const {apiFetch,downloadFile}=useAuth();const [apps,setApps]=useState<Application[]>([]);const [letters,setLetters]=useState<Letter[]>([]);const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const load=useCallback(async()=>{try{const [a,l]=await Promise.all([apiFetch(`${apiBase}/applications`,{cache:"no-store"}),apiFetch(`${apiBase}/cover-letters`,{cache:"no-store"})]);if(!a.ok)throw new Error(await errorText(a));setApps(await a.json() as Application[]);if(l.ok)setLetters(await l.json() as Letter[]);}catch(e){setNotice(e instanceof Error?e.message:"Workflow could not be loaded");}},[apiBase,apiFetch]);useEffect(()=>{let ignore=false;Promise.all([apiFetch(`${apiBase}/applications`,{cache:"no-store"}),apiFetch(`${apiBase}/cover-letters`,{cache:"no-store"})]).then(async([a,l])=>{if(!a.ok)throw new Error(await errorText(a));const nextApps=await a.json() as Application[];const nextLetters=l.ok?await l.json() as Letter[]:[];if(!ignore){setApps(nextApps);setLetters(nextLetters);}}).catch(e=>{if(!ignore)setNotice(e instanceof Error?e.message:"Workflow could not be loaded");});return()=>{ignore=true;};},[apiBase,apiFetch]);
 const shown=useMemo(()=>workflowStatuses[view]?apps.filter(a=>workflowStatuses[view]!.includes(a.status)):apps,[apps,view]);
 const review=async(a:Application,approve:boolean)=>{setBusy(a.id);setNotice(null);try{const r=await apiFetch(`${apiBase}/applications/${a.id}/review`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({approve,reason:approve?"Manually approved after document review":"Rejected after manual review"})});if(!r.ok)throw new Error(await errorText(r));await load();}catch(e){setNotice(e instanceof Error?e.message:"Review failed");}finally{setBusy(null);}};
 const returnToReview=async(a:Application)=>{setBusy(a.id);setNotice(null);try{const r=await apiFetch(`${apiBase}/applications/${a.id}/return-to-review`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Returned for manual review"})});if(!r.ok)throw new Error(await errorText(r));await load();}catch(e){setNotice(e instanceof Error?e.message:"Return to review failed");}finally{setBusy(null);}};
 const markManuallyApplied=async(a:Application)=>{if(!window.confirm("Confirm that you personally completed the external application? This does not submit anything to Ashby."))return;setBusy(a.id);setNotice(null);try{const r=await apiFetch(`${apiBase}/applications/${a.id}/manually-applied`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmed:true,confirmation:"Marked manually applied by authenticated user"})});if(!r.ok)throw new Error(await errorText(r));await load();}catch(e){setNotice(e instanceof Error?e.message:"Manual status update failed");}finally{setBusy(null);}};
 const run=async(a:Application)=>{setBusy(a.id);setNotice(null);try{const r=await apiFetch(`${apiBase}/applications/${a.id}/run`,{method:"POST"});if(!r.ok)throw new Error(await errorText(r));const result=await r.json() as Application;setNotice(result.reason||"Dry run completed without submission.");await load();}catch(e){setNotice(e instanceof Error?e.message:"Dry run failed");}finally{setBusy(null);}};
 if(view==="Cover Letters")return <section className="panel"><div className="panelHead"><div><h2>Cover letters</h2><p>UAE-focused documents generated only from verified facts and matched skills.</p></div></div>{letters.length===0?<div className="state">No cover letters generated yet.</div>:<div className="resumeList">{letters.map(l=><article key={l.id}><div className="fileIcon">DOCX</div><div className="resumeMeta"><h3>{l.title}</h3><p>{l.summary}</p><p>{l.content}</p></div><div className="resumeActions"><button onClick={()=>void downloadFile(`${apiBase}/cover-letters/${l.id}/download?inline=true`,{inline:true})}>Preview</button><button onClick={()=>void downloadFile(`${apiBase}/cover-letters/${l.id}/download`,{filename:l.fileName})}>Download</button></div></article>)}</div>}</section>;
 return <section className="panel"><div className="panelHead"><div><h2>{view}</h2><p>Application packages remain private; all submission actions are dry-run protected by default.</p></div><button className="ghost" onClick={()=>void load()}>Refresh</button></div>{notice&&<div className="notice">{notice}</div>}{shown.length===0?<div className="state">No applications in this stage.</div>:<div className="resumeList">{shown.map(a=><article key={a.id}><div className="fileIcon">{Math.round(a.score)}%</div><div className="resumeMeta"><div><h3>{a.job} · {a.company}</h3><span className={`badge ${a.status.toLowerCase()}`}>{a.status.replaceAll("_"," ")}</span></div><p>Confidence: {a.confidence}{a.adapter?` · ${a.adapter}`:""} · Location fit: {a.locationFit??0}% · Experience fit: {a.experienceFit??0}%</p>{a.scoreExplanation&&<p>{a.scoreExplanation}</p>}<h4>Matched skills</h4><div className="chips good">{a.matchedSkills.map(s=><span key={s}>✓ {s}</span>)}</div><h4>Missing skills</h4><div className="chips">{a.missingSkills.map(s=><span key={s}>{s}</span>)}</div><h4>Mandatory application fields</h4><p>{a.requiredFields.length?a.requiredFields.join(", "):"No public form metadata available."}</p><h4>Missing verified answers</h4><p>{a.missingRequiredAnswers.length?a.missingRequiredAnswers.join(", "):"None"}</p>{a.reason&&<p>{a.reason}</p>}{a.confirmationId&&<p>Confirmation: {a.confirmationId}</p>}</div><div className="resumeActions">{a.resumeVersionId&&<button onClick={()=>void downloadFile(`${apiBase}/resumes/${a.resumeVersionId}/download`,{filename:"tailored-resume.docx"})}>Download tailored résumé</button>}{a.coverLetterId&&<button onClick={()=>void downloadFile(`${apiBase}/cover-letters/${a.coverLetterId}/download`,{filename:"cover-letter.docx"})}>Download cover letter</button>}<a href={a.sourceUrl} target="_blank" rel="noreferrer">View source posting ↗</a>{a.status==="PENDING_REVIEW"&&<><button className="primary" disabled={busy===a.id} onClick={()=>void review(a,true)}>Approve as Ready to Apply</button><button className="danger" disabled={busy===a.id} onClick={()=>void review(a,false)}>Reject</button></>}{(a.status==="READY_TO_APPLY"||a.status==="REJECTED")&&<button disabled={busy===a.id} onClick={()=>void returnToReview(a)}>Return to review</button>}{a.status==="READY_TO_APPLY"&&<><button disabled={busy===a.id} onClick={()=>void run(a)}>Validate Ashby dry run</button><button className="primary" disabled={busy===a.id} onClick={()=>void markManuallyApplied(a)}>Mark manually applied</button></>}</div></article>)}</div>}</section>}
