"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import styles from "./settings.module.css";
import {buildSettingsPayload,emptyProfile,normalizeProfile,Profile,SettingsResponse,validateProfile} from "./settings-form";
type Props={apiBase:string;apiFetch:(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>};
const yesNo=[{value:"Yes",label:"Yes"},{value:"No",label:"No"}];
export default function Settings({apiBase,apiFetch}:Props){
 const[profile,setProfile]=useState<Profile>(emptyProfile),[existing,setExisting]=useState<SettingsResponse>({}),[missing,setMissing]=useState<string[]>([]),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[touched,setTouched]=useState(false),[message,setMessage]=useState(""),[apiError,setApiError]=useState("");
 const errors=useMemo(()=>validateProfile(profile),[profile]),invalid=Object.keys(errors).length>0;
 const completeness=useCallback(async()=>{const r=await apiFetch(`${apiBase}/settings/completeness`,{cache:"no-store"});if(!r.ok)throw new Error();setMissing(((await r.json()) as {missingFields?:string[]}).missingFields||[]);},[apiBase,apiFetch]);
 useEffect(()=>{let active=true;void(async()=>{try{const r=await apiFetch(`${apiBase}/settings`,{cache:"no-store"});if(!r.ok)throw new Error();const body=await r.json() as SettingsResponse;if(active){setExisting(body);setProfile(normalizeProfile(body));}await completeness();}catch{if(active)setApiError("Could not load the applicant profile. Please try again.");}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[apiBase,apiFetch,completeness]);
 const update=<K extends keyof Profile>(key:K,value:Profile[K])=>{setTouched(true);setProfile(p=>({...p,[key]:value}));setMessage("");setApiError("");};
 const submit=async(event:FormEvent)=>{event.preventDefault();setTouched(true);if(invalid||loading||submitting)return;setSubmitting(true);setMessage("");setApiError("");try{const r=await apiFetch(`${apiBase}/settings`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(buildSettingsPayload(profile,existing))});if(!r.ok)throw new Error();const body=await r.json() as SettingsResponse;setExisting(body);setProfile(normalizeProfile(body));await completeness();setMessage("Profile saved successfully.");}catch{setApiError("Could not save the applicant profile. Please review the fields and try again.");}finally{setSubmitting(false);}};
 const error=(key:keyof Profile)=>touched&&errors[key]?<span className={styles.error} id={`${key}-error`}>{errors[key]}</span>:null;
 const options=(current:string,base:{value:string;label:string}[])=>current&&!base.some(o=>o.value===current)?[{value:current,label:current},...base]:base;
 const common=(key:keyof Profile)=>({disabled:loading,"aria-invalid":!!(touched&&errors[key]),"aria-describedby":touched&&errors[key]?`${key}-error`:undefined});
 return <section className={`panel ${styles.panel}`}><div className="panelHead"><div><h2>Verified applicant profile</h2><p>{loading?"Loading profile…":missing.length?`${missing.length} fields still required`:"Profile complete"}</p></div></div><form className={styles.form} onSubmit={event=>void submit(event)} noValidate aria-busy={loading||submitting}><div className={styles.grid}>
  <label className={styles.field}><span>Legal name</span><input type="text" autoComplete="name" value={profile.legalName} onChange={e=>update("legalName",e.target.value)} {...common("legalName")}/>{error("legalName")}</label>
  <label className={styles.field}><span>Application email</span><input type="email" autoComplete="email" value={profile.applicationEmail} onChange={e=>update("applicationEmail",e.target.value)} {...common("applicationEmail")}/>{error("applicationEmail")}</label>
  <label className={styles.field}><span>Phone</span><input type="tel" autoComplete="tel" value={profile.applicationPhone} onChange={e=>update("applicationPhone",e.target.value)} {...common("applicationPhone")}/>{error("applicationPhone")}</label>
  <label className={styles.field}><span>Current location</span><input type="text" autoComplete="address-level2" value={profile.currentLocation} onChange={e=>update("currentLocation",e.target.value)} {...common("currentLocation")}/>{error("currentLocation")}</label>
  <label className={styles.field}><span>UAE relocation status</span><select value={profile.relocation} onChange={e=>update("relocation",e.target.value)} {...common("relocation")}><option value="">Select status</option>{options(profile.relocation,[{value:"UAE",label:"Open to relocate to UAE"},{value:"No",label:"Not open to relocate"}]).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>{error("relocation")}</label>
  <label className={styles.field}><span>Work authorization</span><select value={profile.visaAnswer} onChange={e=>update("visaAnswer",e.target.value)} {...common("visaAnswer")}><option value="">Select answer</option>{options(profile.visaAnswer,yesNo).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>{error("visaAnswer")}</label>
  <label className={styles.field}><span>Sponsorship requirement</span><select value={profile.sponsorshipAnswer} onChange={e=>update("sponsorshipAnswer",e.target.value)} {...common("sponsorshipAnswer")}><option value="">Select answer</option>{options(profile.sponsorshipAnswer,yesNo).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>{error("sponsorshipAnswer")}</label>
  <label className={styles.field}><span>Notice period (days)</span><input type="number" min="0" step="1" inputMode="numeric" value={profile.noticePeriodDays??""} onChange={e=>update("noticePeriodDays",e.target.value===""?null:Number(e.target.value))} {...common("noticePeriodDays")}/>{error("noticePeriodDays")}</label>
  <label className={styles.field}><span>LinkedIn URL</span><input type="url" autoComplete="url" placeholder="https://www.linkedin.com/in/…" value={profile.linkedinUrl} onChange={e=>update("linkedinUrl",e.target.value)} {...common("linkedinUrl")}/>{error("linkedinUrl")}</label>
  <label className={styles.field}><span>Salary expectation <small>Optional</small></span><input type="text" value={profile.salaryAnswer} onChange={e=>update("salaryAnswer",e.target.value)} disabled={loading}/></label>
 </div><fieldset className={styles.declarations}><legend>Consent and declarations</legend><label><input type="checkbox" checked={profile.consentAnswers==="Yes"} onChange={e=>update("consentAnswers",e.target.checked?"Yes":"")} disabled={loading}/> I consent to using these answers to prepare applications.</label>{error("consentAnswers")}<label><input type="checkbox" checked={profile.legalAnswers==="Yes"} onChange={e=>update("legalAnswers",e.target.checked?"Yes":"")} disabled={loading}/> I confirm that the information I entered is accurate.</label></fieldset>
 {apiError&&<p className={styles.apiError} role="alert">{apiError}</p>}{message&&<p className={styles.success} role="status">{message}</p>}<div className={styles.actions}><button className="primary" type="submit" disabled={loading||submitting||invalid}>{submitting?"Saving…":"Save verified profile"}</button></div></form></section>;
}
