package career.assistant.cleanup;
import career.assistant.application.entity.*; import career.assistant.application.repository.ApplicationRepository; import career.assistant.document.entity.*; import career.assistant.document.repository.*; import career.assistant.document.storage.ResumeStorage; import career.assistant.job.repository.JobRepository; import org.springframework.beans.factory.annotation.Value; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.OffsetDateTime; import java.util.*;
@Service public class RetentionCleanupService {private static final Set<ApplicationStatus> INACTIVE=Set.of(ApplicationStatus.REJECTED,ApplicationStatus.ARCHIVED,ApplicationStatus.FAILED);private static final Set<ApplicationStatus> SUCCESS=Set.of(ApplicationStatus.AUTO_APPLIED,ApplicationStatus.MANUALLY_APPLIED);private final ResumeVersionRepository resumes;private final CoverLetterRepository letters;private final ApplicationRepository apps;private final JobRepository jobs;private final CleanupAuditRepository audits;private final ResumeStorage storage;private final boolean enabled,dryRun;private final int unusedDays,rejectedDays,failedDays,successDays;
 public RetentionCleanupService(ResumeVersionRepository r,CoverLetterRepository l,ApplicationRepository a,JobRepository j,CleanupAuditRepository au,ResumeStorage s,@Value("${career.cleanup.enabled:false}")boolean e,@Value("${career.cleanup.dry-run:true}")boolean d,@Value("${career.cleanup.unused-documents-days:30}")int u,@Value("${career.cleanup.rejected-jobs-days:90}")int rejected,@Value("${career.cleanup.failed-attempts-days:90}")int f,@Value("${career.cleanup.successful-applications-days:365}")int success){resumes=r;letters=l;apps=a;jobs=j;audits=au;storage=s;enabled=e;dryRun=d;unusedDays=u;rejectedDays=rejected;failedDays=f;successDays=success;}
 @Scheduled(cron="${career.cleanup.cron:0 30 2 * * *}") @Transactional public void scheduled(){if(enabled)run();}
 @Transactional public CleanupResult run(){int candidates=0,deleted=0;Map<String,Integer> categories=new LinkedHashMap<>();categories.put("APPLICATION",0);categories.put("JOB",0);categories.put("RESUME",0);categories.put("COVER_LETTER",0);OffsetDateTime now=OffsetDateTime.now();
  for(Application a:apps.findByUpdatedAtBefore(now.minusDays(Math.min(failedDays,successDays)))){boolean expired=a.getStatus()==ApplicationStatus.FAILED&&a.getUpdatedAt().isBefore(now.minusDays(failedDays))||SUCCESS.contains(a.getStatus())&&a.getUpdatedAt().isBefore(now.minusDays(successDays));if(!expired)continue;candidates++;categories.compute("APPLICATION",(k,v)->v+1);audit("APPLICATION",a.getId(),null);if(!dryRun){apps.delete(a);deleted++;}}
  for(var j:jobs.findByStatusInAndUpdatedAtBefore(List.of("REJECTED","ARCHIVED"),now.minusDays(rejectedDays))){candidates++;categories.compute("JOB",(k,v)->v+1);audit("JOB",j.getId(),null);if(!dryRun){jobs.delete(j);deleted++;}}
  OffsetDateTime unused=now.minusDays(unusedDays);for(ResumeVersion r:resumes.findByCreatedAtBefore(unused)){if(r.isMasterResume()||apps.existsByResumeVersionIdAndStatusNotIn(r.getId(),INACTIVE))continue;candidates++;categories.compute("RESUME",(k,v)->v+1);audit("RESUME",r.getId(),r.getStoragePath());if(!dryRun){if(r.getStoragePath()!=null)storage.delete(r.getStoragePath());resumes.delete(r);deleted++;}}for(CoverLetter l:letters.findByCreatedAtBefore(unused)){if(apps.existsByCoverLetterIdAndStatusNotIn(l.getId(),INACTIVE))continue;candidates++;categories.compute("COVER_LETTER",(k,v)->v+1);audit("COVER_LETTER",l.getId(),l.getStoragePath());if(!dryRun){if(l.getStoragePath()!=null)storage.delete(l.getStoragePath());letters.delete(l);deleted++;}}return new CleanupResult(dryRun,candidates,deleted,Map.copyOf(categories));}
 private void audit(String category,UUID id,String path){CleanupAuditEntry e=new CleanupAuditEntry();e.setDryRun(dryRun);e.setCategory(category);e.setEntityId(id);e.setStoragePath(path);e.setAction(dryRun?"WOULD_DELETE":"DELETE");e.setDetails("Retention candidate; active master and active application links are protected");audits.save(e);}public record CleanupResult(boolean dryRun,int candidates,int deleted,Map<String,Integer> categories){}
}
