package career.assistant.application.ats;
import org.springframework.stereotype.Component; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.*;
@Component public class AshbySubmissionTransport {
 private static final Set<String> HOSTS=Set.of("jobs.ashbyhq.com","api.ashbyhq.com"); private final HttpClient client;
 public AshbySubmissionTransport(){client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).followRedirects(HttpClient.Redirect.NEVER).build();}
 public AshbySubmissionResult submit(SubmissionPlan plan,boolean dryRun){try{validate(plan);if(dryRun)return new AshbySubmissionResult(AshbySubmissionResult.Outcome.FAILED_BEFORE_SUBMISSION,null,null,"Dry run validated the Ashby multipart plan; no request was submitted.");byte[] body=multipart(plan);HttpRequest request=HttpRequest.newBuilder(URI.create(plan.action())).timeout(Duration.ofSeconds(20)).header("Content-Type","multipart/form-data; boundary="+plan.boundary()).POST(HttpRequest.BodyPublishers.ofByteArray(body)).build();HttpResponse<String> response=client.send(request,HttpResponse.BodyHandlers.ofString());return classify(response.statusCode(),response.body());}catch(IllegalArgumentException e){return AshbySubmissionResult.review(e.getMessage());}catch(HttpTimeoutException|ConnectException e){return new AshbySubmissionResult(AshbySubmissionResult.Outcome.UNCERTAIN,null,null,"Ashby transport timed out or could not connect; manual review is required.");}catch(Exception e){return new AshbySubmissionResult(AshbySubmissionResult.Outcome.UNCERTAIN,null,null,"Ashby transport outcome was uncertain; manual review is required.");}}
 private void validate(SubmissionPlan p){URI u=URI.create(p.action());if(!"https".equalsIgnoreCase(u.getScheme())||!HOSTS.contains(u.getHost().toLowerCase(Locale.ROOT)))throw new IllegalArgumentException("Ashby submission destination is not allowlisted");if(p.fields().isEmpty())throw new IllegalArgumentException("Ashby form schema is empty");for(Attachment a:p.attachments())if(a.bytes().length>6*1024*1024||!Set.of("application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document").contains(a.contentType()))throw new IllegalArgumentException("Attachment type or size is not permitted");}
 private byte[] multipart(SubmissionPlan p){var out=new java.io.ByteArrayOutputStream();try{for(var e:p.fields().entrySet())out.write(("--"+p.boundary()+"\r\nContent-Disposition: form-data; name=\""+e.getKey()+"\"\r\n\r\n"+e.getValue()+"\r\n").getBytes(StandardCharsets.UTF_8));for(Attachment a:p.attachments()){out.write(("--"+p.boundary()+"\r\nContent-Disposition: form-data; name=\""+a.fieldName()+"\"; filename=\""+a.fileName()+"\"\r\nContent-Type: "+a.contentType()+"\r\n\r\n").getBytes(StandardCharsets.UTF_8));out.write(a.bytes());out.write("\r\n".getBytes(StandardCharsets.UTF_8));}out.write(("--"+p.boundary()+"--\r\n").getBytes(StandardCharsets.UTF_8));return out.toByteArray();}catch(java.io.IOException e){throw new IllegalStateException(e);}}
 private AshbySubmissionResult classify(int status,String body){String b=body==null?"":body.toLowerCase(Locale.ROOT);if(b.contains("captcha")||b.contains("challenge"))return AshbySubmissionResult.review("Ashby returned a CAPTCHA or challenge");if(status==400||status==422)return new AshbySubmissionResult(AshbySubmissionResult.Outcome.VALIDATION_FAILED,null,null,"Ashby rejected the submitted fields");if(status>=200&&status<300&&b.matches(".*(confirmation|applicationid|submittedforminstance).*"))return new AshbySubmissionResult(AshbySubmissionResult.Outcome.CONFIRMED,"present",null,"Ashby confirmed submission");if(status>=200&&status<300)return new AshbySubmissionResult(AshbySubmissionResult.Outcome.UNCERTAIN,null,null,"Ashby response did not provide confirmation");return new AshbySubmissionResult(AshbySubmissionResult.Outcome.UNCERTAIN,null,null,"Ashby response was not positively confirmed");}
 public record SubmissionPlan(String action,String boundary,Map<String,String> fields,List<Attachment> attachments){public SubmissionPlan{fields=Map.copyOf(fields);attachments=List.copyOf(attachments);if(boundary==null||boundary.isBlank())boundary="----career-assistant";}} public record Attachment(String fieldName,String fileName,String contentType,byte[] bytes){}
}
