package career.assistant.application.audit;
import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.util.*;
@Service public class SubmissionAttemptService {
 private final SubmissionAttemptRepository repo; public SubmissionAttemptService(SubmissionAttemptRepository r){repo=r;}
 @Transactional public SubmissionAttemptDto recordDryRun(UUID applicationId,String owner,String ats,String source,String key,String request){SubmissionAttempt a=new SubmissionAttempt();a.setApplicationId(applicationId);a.setOwnerSubject(owner);a.setAtsProvider(ats);a.setSourceFingerprint(hash(source));a.setIdempotencyKey(key);a.setRequestFingerprint(hash(request));a.setState(SubmissionAttemptState.DRY_RUN);return SubmissionAttemptDto.of(repo.save(a));}
 @Transactional public SubmissionAttemptDto claim(UUID applicationId,String owner,String ats,String source,String key,String request){
  List<SubmissionAttemptState> blocking=List.of(SubmissionAttemptState.IN_PROGRESS,SubmissionAttemptState.CONFIRMED,SubmissionAttemptState.UNCERTAIN);
  if(repo.findFirstByApplicationIdOrderByCreatedAtDesc(applicationId).filter(a->blocking.contains(a.getState())).isPresent()) throw new SubmissionAttemptConflictException("Application already has a blocking submission attempt");
  if(repo.findFirstBySourceFingerprintAndStateIn(hash(source),blocking).isPresent()) throw new SubmissionAttemptConflictException("Source posting already has a blocking submission attempt");
  SubmissionAttempt a=new SubmissionAttempt();a.setApplicationId(applicationId);a.setOwnerSubject(owner);a.setAtsProvider(ats);a.setSourceFingerprint(hash(source));a.setIdempotencyKey(key);a.setRequestFingerprint(hash(request));a.setState(SubmissionAttemptState.IN_PROGRESS);a.setStartedAt(OffsetDateTime.now());try{return SubmissionAttemptDto.of(repo.saveAndFlush(a));}catch(DataIntegrityViolationException e){throw new SubmissionAttemptConflictException("Submission was claimed concurrently");}
 }
 @Transactional public SubmissionAttemptDto finish(UUID id,SubmissionAttemptState state,String failure,String ref,String url){if(state==SubmissionAttemptState.IN_PROGRESS||state==SubmissionAttemptState.DRY_RUN)throw new IllegalArgumentException("Terminal submission state required");SubmissionAttempt a=repo.findById(id).orElseThrow();a.setState(state);a.setFailureCategory(redact(failure));a.setConfirmationReference(safe(ref));a.setConfirmationUrl(safeUrl(url));a.setCompletedAt(OffsetDateTime.now());return SubmissionAttemptDto.of(repo.save(a));}
 @Transactional(readOnly=true) public List<SubmissionAttemptDto> listOwned(String owner){return repo.findByOwnerSubjectOrderByCreatedAtDesc(owner).stream().map(SubmissionAttemptDto::of).toList();}
 @Transactional(readOnly=true) public boolean dailyLimitAvailable(String owner,int limit){OffsetDateTime from=LocalDate.now(ZoneOffset.UTC).atStartOfDay().atOffset(ZoneOffset.UTC);return repo.countByOwnerSubjectAndStateAndCompletedAtGreaterThanEqualAndCompletedAtLessThan(owner,SubmissionAttemptState.CONFIRMED,from,from.plusDays(1))<limit;}
 private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest((v==null?"":v).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private String redact(String v){return v==null?null:v.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9_-]+","_").substring(0,Math.min(100,v.length()));} private String safe(String v){return v==null?null:v.length()>500?v.substring(0,500):v;} private String safeUrl(String v){return v==null?null:(v.startsWith("https://")&&v.length()<=1000?v:null);}
 public static class SubmissionAttemptConflictException extends RuntimeException{public SubmissionAttemptConflictException(String m){super(m);}}
}
