package career.assistant.settings.entity;
import jakarta.persistence.*; import java.time.OffsetDateTime; import java.util.UUID;
@Entity @Table(name="user_settings") public class UserSettings {
 @Id private UUID id=UUID.fromString("00000000-0000-0000-0000-000000000001");
 @Column(name="owner_subject", nullable=false, unique=true) private String ownerSubject;
 @Column(name="profile_name") private String profileName; private String locations; private String roles; private String skills;
 @Column(name="experience_min") private Integer experienceMin; @Column(name="experience_max") private Integer experienceMax;
 @Column(name="dry_run") private boolean dryRun=true; @Column(name="current_location") private String currentLocation="India"; private String relocation="UAE";
 @Column(name="notice_period_days") private Integer noticePeriodDays=90; @Column(name="notification_recipient") private String notificationRecipient;
 @Column(name="visa_answer") private String visaAnswer; @Column(name="salary_answer") private String salaryAnswer; @Column(name="sponsorship_answer") private String sponsorshipAnswer; @Column(name="legal_answers") private String legalAnswers;
 @Column(name="legal_name") private String legalName; @Column(name="application_email") private String applicationEmail; @Column(name="application_phone") private String applicationPhone; @Column(name="linkedin_url") private String linkedinUrl; @Column(name="consent_answers") private String consentAnswers;
 @Column(name="updated_at") private OffsetDateTime updatedAt; @PrePersist @PreUpdate void stamp(){updatedAt=OffsetDateTime.now();}
 public UUID getId(){return id;} public void setId(UUID v){id=v;} public String getOwnerSubject(){return ownerSubject;} public void setOwnerSubject(String v){ownerSubject=v;} public String getProfileName(){return profileName;} public void setProfileName(String v){profileName=v;} public String getLocations(){return locations;} public void setLocations(String v){locations=v;} public String getRoles(){return roles;} public void setRoles(String v){roles=v;} public String getSkills(){return skills;} public void setSkills(String v){skills=v;} public Integer getExperienceMin(){return experienceMin;} public void setExperienceMin(Integer v){experienceMin=v;} public Integer getExperienceMax(){return experienceMax;} public void setExperienceMax(Integer v){experienceMax=v;} public boolean isDryRun(){return dryRun;} public void setDryRun(boolean v){dryRun=v;} public String getCurrentLocation(){return currentLocation;} public void setCurrentLocation(String v){currentLocation=v;} public String getRelocation(){return relocation;} public void setRelocation(String v){relocation=v;} public Integer getNoticePeriodDays(){return noticePeriodDays;} public void setNoticePeriodDays(Integer v){noticePeriodDays=v;} public String getNotificationRecipient(){return notificationRecipient;} public void setNotificationRecipient(String v){notificationRecipient=v;} public String getVisaAnswer(){return visaAnswer;} public void setVisaAnswer(String v){visaAnswer=v;} public String getSalaryAnswer(){return salaryAnswer;} public void setSalaryAnswer(String v){salaryAnswer=v;} public String getSponsorshipAnswer(){return sponsorshipAnswer;} public void setSponsorshipAnswer(String v){sponsorshipAnswer=v;} public String getLegalAnswers(){return legalAnswers;} public void setLegalAnswers(String v){legalAnswers=v;} public String getLegalName(){return legalName;} public void setLegalName(String v){legalName=v;} public String getApplicationEmail(){return applicationEmail;} public void setApplicationEmail(String v){applicationEmail=v;} public String getApplicationPhone(){return applicationPhone;} public void setApplicationPhone(String v){applicationPhone=v;} public String getLinkedinUrl(){return linkedinUrl;} public void setLinkedinUrl(String v){linkedinUrl=v;} public String getConsentAnswers(){return consentAnswers;} public void setConsentAnswers(String v){consentAnswers=v;} public OffsetDateTime getUpdatedAt(){return updatedAt;}
}
